# Chemistry training config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: data/qm9

# Hyperparams - Training
global_batch_size: 64

epochs: 1000
eval_interval: 100
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Optimizer hyperparameters
beta1: 0.9
beta2: 0.95
weight_decay: 0.1

# Chemistry-specific hyperparameters
cutoff_radius: 5.0
energy_weight: 1.0
force_weight: 1.0
